[sinks.qovery]
title = "Qovery"
noun = "another Qovery instance"
beta = true
common = false
delivery_guarantee = "best_effort"
egress_method = "streaming"
features = [
  "Send data to another downstream Qovery instance.",
]
function_category = "transmit"
healthcheck = true
input_types = ["log", "metric"]
requirements = {}
write_to_description = "another downstream [`qovery` source][docs.sources.qovery]"

<%= render("_partials/fields/_component_options.toml", type: "sink", name: "qovery") %>

<%= render(
  "_partials/fields/_buffer_options.toml",
  namespace: "sinks.qovery.options",
  common: false
) %>

[sinks.qovery.options.address]
type = "string"
common = true
examples = ["92.12.333.224:5000"]
required = true
description = """\
The downstream Qovery address to connect to. The address _must_ include a port.\
"""

<%= render("_partials/fields/_tls_connector_options.toml", namespace: "sinks.qovery.options", can_enable: true, can_verify_certificate: true, can_verify_hostname: true) %>
