#
# Subdomains
#

[[redirects]]
  from = "https://qovery-project.netlify.com/*"
  to = "https://qovery.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://chat.qovery.dev/*"
  to = "https://gitter.im/timberio-qovery/community"
  status = 302
  force = true

[[redirects]]
  from = "https://sh.qovery.dev/*"
  to = "http://sh.qovery.dev.s3-website-us-east-1.amazonaws.com/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://test-results.qovery.dev/*"
  to = "http://test-results.qovery.dev.s3-website-us-east-1.amazonaws.com/:splat"
  status = 200
  force = true

#
# Old docs site
#

[[redirects]]
  from = "https://docs.qovery.dev/v/:version/*"
  to = "https://docs.qovery.dev/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.qovery.dev/correctness"
  to = "https://qovery.dev/#correctness"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.qovery.dev/performance"
  to = "https://qovery.dev/#performance"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.qovery.dev/usage/administration"
  to = "https://qovery.dev/docs/administration/"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.qovery.dev/usage/administration/stopping"
  to = "https://qovery.dev/docs/administration/process-management/#stopping"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.qovery.dev/usage/administration/reloading"
  to = "https://qovery.dev/docs/administration/process-management/#reloading"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.qovery.dev/usage/administration/starting"
  to = "https://qovery.dev/docs/administration/process-management/#starting"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.qovery.dev/usage/administration/*"
  to = "https://qovery.dev/docs/administration/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.qovery.dev/usage/configuration"
  to = "https://qovery.dev/docs/setup/configuration/"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.qovery.dev/usage/configuration/*"
  to = "https://qovery.dev/docs/reference/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://docs.qovery.dev/*"
  to = "https://qovery.dev/docs/:splat"
  status = 301
  force = true

#
# Internal redirects
#
# Sorted by the `from` attribute.
#

[[redirects]]
  from = "/blog/tags/announcement/"
  to = "/blog/tags/type-announcement/"
  status = 301
  force = true

[[redirects]]
  from = "/docs/"
  to = "/docs/about/what-is-qovery/"
  status = 302
  force = true

[[redirects]]
  from = "/docs/about/correctness"
  to = "https://qovery.dev/#correctness"
  status = 301
  force = true

[[redirects]]
  from = "/docs/about/performance"
  to = "https://qovery.dev/#performance"
  status = 301
  force = true

[[redirects]]
  from = "/docs/components/*"
  to = "/docs/reference/:splat"
  status = 302
  force = true

[[redirects]]
  from = "/docs/configuration"
  to = "/docs/setup/configuration/"
  status = 301
  force = true

[[redirects]]
  from = "/docs/setup/deployment/roles/"
  to = "/docs/setup/deployment/strategies/"
  status = 301
  force = true

[[redirects]]
  from = "/docs/setup/deployment/roles/agent/"
  to = "/docs/setup/deployment/strategies/#daemon"
  status = 301
  force = true

[[redirects]]
  from = "/docs/setup/deployment/roles/service/"
  to = "/docs/setup/deployment/strategies/#service"
  status = 301
  force = true

[[redirects]]
  from = "/docs/setup/getting-started"
  to = "/guides/getting-started/"
  status = 301
  force = true

[[redirects]]
  from = "/docs/setup/guides/"
  to = "/guides/"
  status = 301
  force = true

[[redirects]]
  from = "/docs/setup/guides/advanced-configs/"
  to = "/guides/advanced/managing-complex-configs/"
  status = 301
  force = true

[[redirects]]
  from = "/docs/setup/guides/getting-started/"
  to = "/guides/getting-started/"
  status = 301
  force = true

[[redirects]]
  from = "/docs/setup/guides/troubleshooting"
  to = "/guides/getting-started/troubleshooting/"
  status = 301
  force = true

[[redirects]]
  from = "/docs/setup/guides/unit-testing"
  to = "/guides/advanced/unit-testing/"
  status = 301
  force = true

[[redirects]]
  from = "/docs/setup/installation/containers/"
  to = "/docs/setup/installation/platforms/"
  status = 301
  force = true

[[redirects]]
  from = "/docs/setup/installation/containers/docker/"
  to = "/docs/setup/installation/platforms/docker"
  status = 301
  force = true

[[redirects]]
  from = "/docs/setup/installation/deployment/roles/agent/"
  to = "/docs/setup/installation/deployment/strategies/#daemon"
  status = 301
  force = true

[[redirects]]
  from = "/docs/setup/installation/deployment/roles/service/"
  to = "/docs/setup/installation/deployment/strategies/#service"
  status = 301
  force = true

[[redirects]]
  from = "/docs/setup/installation/package-managers/yum"
  to = "/docs/setup/installation/package-managers/rpm/"
  status = 301
  force = true

[[redirects]]
  from = "/docs/reference/sinks/s3"
  to = "/docs/reference/sinks/aws_s3/"
  status = 301
  force = true

[[redirects]]
  from = "/docs/reference/sinks/tcp/"
  to = "/docs/reference/sinks/socket/"
  status = 301
  force = true

[[redirects]]
  from = "/docs/reference/sources/tcp/"
  to = "/docs/reference/sources/socket/"
  status = 301
  force = true

[[redirects]]
  from = "/docs/reference/sources/udp/"
  to = "/docs/reference/sources/socket/"
  status = 301
  force = true

[[redirects]]
  from = "/docs/usage/*"
  to = "/docs/administration/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/download/"
  to = "/releases/latest/download/"
  status = 302
  force = true

[[redirects]]
  from = "/mailing_list/"
  to = "/community/"
  status = 301
  force = true

[[redirects]]
  from = "/releases/"
  to = "/releases/latest/download/"
  status = 302
  force = true
