#                                    __   __  __
#                                    \ \ / / / /
#                                     \ V / / /
#                                      \_/  \/
#
#                                    V E C T O R
#                            Configuration Specification
#
# ------------------------------------------------------------------------------
# Website: https://docs.qovery.com
# Docs: https://docs.qovery.com
# Community: https://discord.qovery.com/
# ------------------------------------------------------------------------------
# The file contains a full specification for the `vector.toml` configuration
# file. It follows the TOML format and includes all options, types, and
# possible values.
#
# More info on Vector's configuration can be found at:
# /docs/setup/configuration/

# ------------------------------------------------------------------------------
# Global
# ------------------------------------------------------------------------------
# Global options are relevant to Vector as a whole and apply to global behavior.

#
# General
#

# The directory used for persisting Qovery state, such as on-disk buffers, file
# checkpoints, and more. Please make sure the Qovery project has write
# permissions to this dir.
#
# * optional
# * no default
# * type: string
data_dir = "/var/lib/qovery"

# The list of DNS servers Qovery will use to resolve DNS requests. When set
# Qovery will ignore the system configuration and use only the list of DNS
# servers provided. If this option is not set then Qovery will attempt to use
# the system configuration.
#
# * optional
# * no default
# * type: [string]
dns_servers = ["0.0.0.0:53"]

#
# Log schema
#

[.log_schema]
  # The key used to hold the log host. See the log data model page for more info.
  #
  # * optional
  # * default: "host"
  # * type: string
  host_key = "host"
  host_key = "@host"
  host_key = "instance"
  host_key = "machine"

  # The key under which Kubernetes related fields are nested.
  #
  # * optional
  # * default: "kubernetes"
  # * type: string
  kubernetes_key = "kubernetes"
  kubernetes_key = "kube"
  kubernetes_key = "k8s"

  # The key used to hold the log message. See the log data model page for more
  # info.
  #
  # * optional
  # * default: "message"
  # * type: string
  message_key = "message"
  message_key = "@message"
  message_key = "msg"

  # The key used to hold the log source. See the log data model page for more
  # info.
  #
  # * optional
  # * default: "source"
  # * type: string
  source_key = "source"
  source_key = "@source"
  source_key = "src"

  # The key used to hold the log source type. See the log data model page for
  # more info.
  #
  # * optional
  # * default: "source_type"
  # * type: string
  source_type_key = "source_type"
  source_type_key = "@source_type"
  source_type_key = "src_ty"

  # The key used to represent when the log was generated. See the log data model
  # page for more info.
  #
  # * optional
  # * default: "timestamp"
  # * type: string
  timestamp_key = "timestamp"
  timestamp_key = "@timestamp"
  timestamp_key = "datetime"

# ------------------------------------------------------------------------------
# Sources
# ------------------------------------------------------------------------------
# Sources specify data sources and are responsible for ingesting data into
# Vector.


# ------------------------------------------------------------------------------
# Transforms
# ------------------------------------------------------------------------------
# Transforms parse, structure, and enrich events.


# ------------------------------------------------------------------------------
# Sinks
# ------------------------------------------------------------------------------
# Sinks batch or stream data out of Vector.
