# Interfaces
#
# Interfaces represents interfaces through which you can install Qovery.
# This can be a platform, package manager, CLI utility, etc. Anything that
# can install Qovery.
#
# Operating systems and platforms must specify which interfaces they support.

[installation.interfaces.docker-cli]
archs = ["x86_64", "ARM64", "ARMv7"]
config_path = "/etc/qovery/qovery.toml"
title = "Docker CLI"
type = "platform"

[installation.interfaces.docker-compose]
archs = ["x86_64", "ARM64", "ARMv7"]
config_path = "/etc/qovery/qovery.toml"
title = "Docker Compose"
type = "platform"

[installation.interfaces.dpkg]
archs = ["x86_64", "ARM64", "ARMv7"]
config_path = "/etc/qovery/qovery.toml"
title = "DPKG"
type = "package_manager"

[installation.interfaces.homebrew]
archs = ["x86_64"]
config_path = "/etc/qovery/qovery.toml"
title = "Homebrew"
type = "package_manager"

[installation.interfaces.msi]
archs = ["x86_64"]
config_path = "config\\qovery.toml"
title = "MSI"
type = "package_manager"

[installation.interfaces.nix]
archs = ["x86_64"]
config_path = "/etc/qovery/qovery.toml"
title = "Nix"
type = "package_manager"

[installation.interfaces.rpm]
archs = ["x86_64"]
config_path = "/etc/qovery/qovery.toml"
title = "RPM"
type = "package_manager"

[installation.interfaces.qovery-cli]
archs = ["x86_64", "ARM64", "ARMv7"]
config_path = "qovery.toml"
title = "Qovery CLI"
type = "none"
