[installation.operating_systems.amazon-linux]
title = "Amazon Linux"
interfaces = [
  "rpm",
  "qovery-cli",
  "docker-cli",
  "docker-compose",
]
os = "Linux"
strategies = [
  {name = "daemon", source = "journald"},
]

[installation.operating_systems.centos]
title = "CentOS"
interfaces = [
  "rpm",
  "qovery-cli",
  "docker-cli",
  "docker-compose",
]
os = "Linux"
strategies = [
  {name = "daemon", source = "journald"},
]

[installation.operating_systems.debian]
title = "Debian"
interfaces = [
  "dpkg",
  "qovery-cli",
  "docker-cli",
  "docker-compose",
]
os = "Linux"
strategies = [
  {name = "daemon", source = "journald"},
]

[installation.operating_systems.macos]
title = "MacOS"
interfaces = [
  "homebrew",
  "qovery-cli",
  "docker-cli",
  "docker-compose",
]
os = "Linux"
strategies = [
  {name = "daemon", source = "file"},
]

[installation.operating_systems.nixos]
title = "NixOS"
interfaces = [
  "nix",
  "qovery-cli",
  "docker-cli",
  "docker-compose",
]
os = "Linux"
strategies = [
  {name = "daemon", source = "journald"},
]

[installation.operating_systems.raspbian]
title = "Raspbian"
interfaces = [
  "qovery-cli",
  "docker-cli",
  "docker-compose",
]
os = "Linux"
strategies = [
  {name = "daemon", source = "journald"}
]

[installation.operating_systems.rhel]
title = "RHEL"
interfaces = [
  "rpm",
  "qovery-cli",
  "docker-cli",
  "docker-compose",
]
os = "Linux"
strategies = [
  {name = "daemon", source = "journald"},
]

[installation.operating_systems.ubuntu]
title = "Ubuntu"
interfaces = [
  "dpkg",
  "qovery-cli",
  "docker-cli",
  "docker-compose",
]
os = "Linux"
strategies = [
  {name = "daemon", source = "journald"},
]

[installation.operating_systems.windows]
title = "Windows"
interfaces = [
  "msi",
  "qovery-cli",
  "docker-cli",
  "docker-compose",
]
os = "Windows"
strategies = [
  {name = "daemon", source = "file"},
]
