[[cli.global_options]]
gnu = "color"
type = "string"
description = "Read configuration from the specified file"

[[cli.global_options]]
default = "/etc/qovery/qovery.toml"
gnu = "config"
posix = "c"
type = "string"
description = "Read configuration from the specified file"
