[[databases]]
name = "mysql"
logo_path = "/img/logos/docker.svg"
dark_logo_path = "/img/logos/docker.svg"

[[databases]]
name = "postgresql"
logo_path = "/img/logos/docker.svg"
dark_logo_path = "/img/logos/docker.svg"

[[databases]]
name = "mongodb"
logo_path = "/img/logos/docker.svg"
dark_logo_path = "/img/logos/docker.svg"
