[[frameworks]]
name = "hasura"
logo_path = "/img/logos/hasura.svg"
dark_logo_path = "/img/logos/hasura_white.svg"

[[frameworks]]
name = "laravel"
logo_path = "/img/logos/laravel.svg"
dark_logo_path = "/img/logos/laravel.svg"

[[frameworks]]
name = "springboot"
logo_path = "/img/logos/springboot.svg"
dark_logo_path = "/img/logos/springboot.svg"

[[frameworks]]
name = "nodejs"
logo_path = "/img/logos/nodejs.svg"
dark_logo_path = "/img/logos/nodejs.svg"

[[frameworks]]
name = "flask"
logo_path = "/img/logos/flask.svg"
dark_logo_path = "/img/logos/flask_white.svg"

[[frameworks]]
name = "jhipster"
logo_path = "/img/logos/jhipster.svg"
dark_logo_path = "/img/logos/jhipster.svg"

[[frameworks]]
name = "gin"
logo_path = "/img/logos/gin.svg"
dark_logo_path = "/img/logos/gin.svg"

[[frameworks]]
name = "rails"
logo_path = "/img/logos/rails.svg"
dark_logo_path = "/img/logos/rails.svg"

[[frameworks]]
name = "django"
logo_path = "/img/logos/django.svg"
dark_logo_path = "/img/logos/django.svg"


[[frameworks]]
name = "deno"
logo_path = "/img/logos/deno.svg"
dark_logo_path = "/img/logos/deno.svg"
