[[languages]]
name = "php"
logo_path = "/img/logos/php.svg"
dark_logo_path = "/img/logos/php.svg"

[[languages]]
name = "kotlin"
logo_path = "/img/logos/kotlin.svg"
dark_logo_path = "/img/logos/kotlin.svg"

[[languages]]
name = "java"
logo_path = "/img/logos/java.svg"
dark_logo_path = "/img/logos/java.svg"

[[languages]]
name = "javascript"
logo_path = "/img/logos/javascript.svg"
dark_logo_path = "/img/logos/javascript.svg"

[[languages]]
name = "python"
logo_path = "/img/logos/python.svg"
dark_logo_path = "/img/logos/python.svg"

[[languages]]
name = "rust"
logo_path = "/img/logos/rust.svg"
dark_logo_path = "/img/logos/rust_white.svg"

[[languages]]
name = "go"
logo_path = "/img/logos/go.svg"
dark_logo_path = "/img/logos/go.svg"

[[languages]]
name = "ruby"
logo_path = "/img/logos/ruby.svg"
dark_logo_path = "/img/logos/ruby.svg"

[[languages]]
name = "scala"
logo_path = "/img/logos/scala.svg"
dark_logo_path = "/img/logos/scala.svg"
