[options.data_dir]
type = "string"
examples = ["/var/lib/qovery"]
description = """\
The directory used for persisting Qovery state, such as on-disk buffers, \
file checkpoints, and more. Please make sure the Qovery project has write \
permissions to this dir.\
"""

[options.dns_servers]
type = "[string]"
examples = [["0.0.0.0:53"]]
description = """\
The list of DNS servers Qovery will use to resolve DNS requests. When set \
Qovery will ignore the system configuration and use only the list of DNS \
servers provided. If this option is not set then Qovery will attempt to use \
the system configuration.\
"""

[options.log_schema]
type = "table"
description = """\
The default log schema that all Qovery components operate on. See the \
[log data model page][docs.data-model.log] for more info.
"""

[options.log_schema.children.host_key]
type = "string"
default = "host"
examples = ["host", "@host", "instance", "machine"]
description = """\
The key used to hold the log host. See the \
[log data model page][docs.data-model.log#host] for more info.\
"""

[options.log_schema.children.message_key]
type = "string"
default = "message"
examples = ["message", "@message", "msg"]
description = """\
The key used to hold the log message. See the \
[log data model page][docs.data-model.log#message] for more info.\
"""

[options.log_schema.children.timestamp_key]
type = "string"
default = "timestamp"
examples = ["timestamp", "@timestamp", "datetime"]
description = """\
The key used to represent when the log was generated. See the \
[log data model page][docs.data-model.log#timestamp] for more info.\
"""

[options.log_schema.children.kubernetes_key]
type = "string"
default = "kubernetes"
examples = ["kubernetes", "kube", "k8s"]
description = "The key under which Kubernetes related fields are nested."

[options.log_schema.children.source_key]
type = "string"
default = "source"
examples = ["source", "@source", "src"]
description = """\
The key used to hold the log source. See the \
[log data model page][docs.data-model.log#source] for more info.\
"""

[options.log_schema.children.source_type_key]
type = "string"
default = "source_type"
examples = ["source_type", "@source_type", "src_ty"]
description = """\
The key used to hold the log source type. See the \
[log data model page][docs.data-model.log#source_type] for more info.\
"""
