[[team]]
id = "romaric"
avatar = "https://github.com/evoxmusic.png"
github = "https://github.com/evoxmusic"
keybase = "https://keybase.io/evoxmusic"
name = "Romaric P."
bio = """\
Romaric is a Software Engineer, and CEO at <a href=\"https://www.qovery.com\">Qovery</a>. \
He has 10+ years of experience in R&D. From the ad-tech to the financial industry, he has deep expertise in reliable and performant systems.
"""

[[team]]
id = "pierre"
avatar = "https://github.com/deimosfr.png"
github = "https://github.com/deimosfr"
keybase = "https://keybase.io/pierre"
name = "Pierre M."
bio = """\
Pierre is a Software Engineer, and CTO at <a href=\"https://www.qovery.com\">Qovery</a>. \
"""

[[team]]
id = "patryk"
avatar = "https://github.com/pjeziorowski.png"
github = "https://github.com/pjeziorowski"
keybase = "https://keybase.io/patryk"
name = "Patryk J."
bio = """\
Patryk is an experienced Software Engineer, and Developer Advocate at <a href=\"https://www.qovery.com\">Qovery</a>. \
"""

[[team]]
id = "mehdi"
avatar = "https://github.com/sileht.png"
github = "https://github.com/sileht"
keybase = "https://keybase.io/mehdi"
name = "Mehdi A."
bio = """\
Mehdi is an experienced Software Engineer at <a href=\"https://www.qovery.com\">Qovery</a>. \
"""
