[[team]]
id = "romaric"
avatar = "https://github.com/evoxmusic.png"
github = "https://github.com/evoxmusic"
keybase = "https://keybase.io/evoxmusic"
name = "Romaric"
bio = """\
Romaric is a Software Engineer and CEO at <a href=\"https://www.qovery.com\">Qovery</a> \
"""

[[team]]
id = "pierre"
avatar = "https://github.com/deimosfr.png"
github = "https://github.com/deimosfr"
keybase = "https://keybase.io/pierre"
name = "Pierre"
bio = """\
Pierre is a Software Engineer and CTO at <a href=\"https://www.qovery.com\">Qovery</a> \
"""

[[team]]
id = "patryk"
avatar = "https://github.com/pjeziorowski.png"
github = "https://github.com/pjeziorowski"
keybase = "https://keybase.io/patryk"
name = "Patryk"
bio = """\
Patryk is a Developer Advocate at <a href=\"https://www.qovery.com\">Qovery</a> \
"""

[[team]]
id = "mehdi"
avatar = "https://github.com/sileht.png"
github = "https://github.com/sileht"
keybase = "https://keybase.io/mehdi"
name = "Mehdi"
bio = """\
Mehdi is a Software Engineer at <a href=\"https://www.qovery.com\">Qovery</a> \
"""
